 
language: node_js
node_js:
  - "stable"
services:
  - postgresql
addons:
  postgresql: "15.2"
cache:
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - psql -c 'create database taxi24_qik;' -U postgres
  - yarn run db:create
  - cd app/v1/
script:
  - yarn test
after_success:
  - yarn run coverage
